services:
  database:
    build: ./mongodb_rs
    container_name: database
    restart: always
    ports:
      - "27017:27017"
    healthcheck:
      test: ['CMD', 'mongo', 'docker', '--port', '27017', '--eval', "db.adminCommand('ping').ok"]
      interval: 10s
      timeout: 2s
      retries: 6
      start_period: 20s
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: docker
      MONGO_INITDB_DATABASE: aliasgame
      MONGO_REPLICA_HOST: localhost
      MONGO_REPLICA_PORT: 27017
    volumes:                        
      - mongodata:/data/mongo 
    networks:
      - my_network
    
  app:
    build: .
    container_name: app
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env.exemple
    links:
      - database
    networks:
      - my_network
    depends_on:
      database: 
        condition: service_healthy

networks:
   my_network:
    driver: bridge  
  
volumes:                         
  mongodata:
    driver: local
